version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:18.17.0

jobs:
  security-checks:
    executor: node_executor
    steps:
      - checkout

      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl unzip python3-pip
            pip install bandit

      - run:
          name: Run Bandit on test cases
          command: |
            echo "Running Bandit in test-cases/bandit"
            bandit -r test-cases/bandit -ll || echo "Bandit found issues"

workflows:
  version: 2
  check-security:
    jobs:
      - security-checks
