      - run:
          name: Create promtail config file
          command: |
            echo 'Creating promtail-config.yml'
            mkdir -p ./tmp
            cat <<EOF > ./tmp/promtail-config.yml
            server:
              http_listen_port: 9080
              grpc_listen_port: 0
            positions:
              filename: /tmp/positions.yaml
            clients:
              - url: http://loki:3100/loki/api/v1/push
            scrape_configs:
              - job_name: docker
                static_configs:
                  - targets:
                      - localhost
                    labels:
                      job: docker-logs
                      __path__: /var/lib/docker/containers/*/*.log
            EOF
            ls -l ./tmp

      - run:
          name: Start Promtail
          command: |
            docker run -d --name promtail --network=loki-net \
              -v /var/lib/docker/containers:/var/lib/docker/containers:ro \
              -v $PWD/tmp/promtail-config.yml:/etc/promtail/config.yml \
              grafana/promtail:2.9.2 -config.file=/etc/promtail/config.yml
