version: 2.1

jobs:
  zap-scan:
    docker:
      - image: zaproxy/zap-stable
    working_directory: /zap/wrk  # This resolves the error
    steps:
      - checkout
      - run:
          name: Run ZAP Baseline Scan
          command: >
            zap-baseline.py
            -t https://hoobank.netlify.app
            -r zap-report.html
      - store_artifacts:
          path: /zap/wrk/zap-report.html
          destination: zap-report

workflows:
  version: 2
  zap-workflow:
    jobs:
      - zap-scan
