version: 2.1

jobs:
  checkov-scan:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Install Checkov
          command: |
            python -m pip install --upgrade pip
            pip install checkov

      - run:
          name: Run Checkov on Terraform Files
          command: |
            checkov -d .test-cases/iac/ --output json --soft-fail > checkov-report.json

      - persist_to_workspace:
          root: .
          paths:
            - checkov-report.json

workflows:
  checkov_workflow:
    jobs:
      - checkov-scan:
          filters:
            branches:
              only: main
