jobs:
  nuclei_scan:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install Nuclei
          command: |
            curl -LO https://github.com/projectdiscovery/nuclei/releases/download/v3.4.3/nuclei_3.4.3_linux_amd64.zip
            unzip -o nuclei_3.4.3_linux_amd64.zip
            sudo mv nuclei /usr/local/bin/
            nuclei -version
      - run:
          name: Run Nuclei Scan
          command: |
            TARGET_URL="https://demo.testfire.net"
            nuclei -u "$TARGET_URL" -o nuclei-report.txt || echo "Nuclei scan completed with non-zero exit"
      - store_artifacts:
          path: nuclei-report.txt
          destination: nuclei-report
