version: 2.1

jobs:
  build:
    docker:
      - image: zaproxy/zap-stable:latest  # Use the correct image from Docker Hub
    steps:
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker

      - run:
          name: Docker login
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Run OWASP ZAP Scan
          command: |
            TARGET_URL="https://hoobank.netlify.app"
            docker run --rm -t zaproxy/zap-stable zap-baseline.py -t "$TARGET_URL" -g gen.conf -r zap-report.html

      - store_artifacts:
          path: zap-report.html
          destination: zap-report

workflows:
  version: 2
  scan-and-test:
    jobs:
      - build
