version: 2.1

jobs:
  sqlmap_scan:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install SQLMap
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
            pip3 install sqlmap
      - run:
          name: Run SQLMap Scan
          command: |
            TARGET_URL="https://demo.testfire.net/"
            sqlmap -u "$TARGET_URL" --batch --risk=3 --level=5 --crawl=1 --random-agent --output-dir=sqlmap-output
            timeout 100s sqlmap -u "$TARGET_URL" \
              --batch --risk=3 --level=5 --crawl=1 --random-agent \
              --output-dir=sqlmap-output || true
      - store_artifacts:
          path: sqlmap-output
          destination: sqlmap-report

workflows:
  version: 2
  secure_build_pipeline:
    jobs:
      - sqlmap_scan
