version: 2.1

jobs:
  sqlmap_scan:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install SQLMap
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
            pip3 install sqlmap
      - run:
          name: Run SQLMap Scan (timeout after 1 minute)
          command: |
            TARGET_URL="https://demo.testfire.net/"
            echo "Starting SQLMap scan on $TARGET_URL (1-minute timeout)..."
            timeout --foreground --kill-after=10s 60s \
              sqlmap -u "$TARGET_URL" --batch --risk=3 --level=5 --crawl=1 --random-agent --output-dir=sqlmap-output || \
              echo "SQLMap scan timed out or exited with non-zero status."
      - store_artifacts:
          path: sqlmap-output
          destination: sqlmap-report

workflows:
  version: 2
  secure_build_pipeline:
    jobs:
      - sqlmap_scan
