version: 2.1

orbs:
  snyk: snyk/snyk@1.6.0

jobs:
  build:
    docker:
      - image: cimg/node:18.20.2  # Modern image with Node.js
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - snyk/scan:
          monitor-on-build: true  # optional: sends results to Snyk dashboard
          fail-on-issues: false   # prevent build from failing on vulnerabilities

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
