version: 2.1

orbs:
  eslint: arrai/eslint@8.1.0

jobs:
  build:
    docker:
      - image: cimg/node:18.20.2  # Modern image with Node.js
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - eslint/lint:   # Corrected to use the `lint` command from the ESLint orb
          files: "lib/**"  # Specify the files to lint (adjust as necessary)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - build
