version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0-node  # Includes both Node.js and Java

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            npm install

      - run:
          name: Run ESLint
          command: |
            npx eslint . --ext .js,.jsx,.ts,.tsx || echo "ESLint found issues"

      - run:
          name: Build React App
          command: |
            npm run build

      - run:
          name: Run OWASP Dependency Check
          command: |
            wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
            unzip dependency-check-8.4.0-release.zip
            ./dependency-check/bin/dependency-check.sh --scan . --format HTML --out reports

      - store_artifacts:
          path: reports
          destination: dependency-check-report

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
