version: 2.1

jobs:
  sqlmap_scan:
    machine:  # Full VM to install tools and access network
      image: ubuntu-2204:current

    steps:
      - checkout

      - run:
          name: Install SQLMap
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
            pip3 install sqlmap

      - run:
          name: Run SQLMap Scan
          command: |
            # Replace the target URL with your actual endpoint
            TARGET_URL="https://hoooobank.netlify.app/login"
            sqlmap -u "$TARGET_URL" --batch --risk=3 --level=5 --crawl=1 --random-agent --output-dir=sqlmap-output

      - store_artifacts:
          path: sqlmap-output
          destination: sqlmap-report
