jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Install Bandit
          command: |
            pip install bandit

      - run:
          name: Run Bandit on Test Case File
          command: |
            bandit /test-cases/bandit/test_vuln.py -f json -o bandit_report.json || true

      - store_artifacts:
          path: bandit_report.json
          destination: bandit-scan-report
