version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:18.17.0

jobs:
  build:
    executor: node_executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            npm ci

      - run:
          name: Build React App
          command: |
            npm run build

      - run:
          name: Run OWASP Dependency Check
          command: |
            wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
            unzip dependency-check-8.4.0-release.zip
            ./dependency-check/bin/dependency-check.sh --scan . --format HTML --out reports

      - store_artifacts:
          path: reports
          destination: dependency-check-report

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
