version: 2.1

orbs:
  eslint: arrai/eslint@8.1.0

jobs:
  build:
    docker:
      - image: cimg/node:18.20.2

    steps:
      - checkout
      - run: npm install
      - eslint/lint:
          wd: ~/project
          files: src/**    # or . if you want the whole repo scanned
          npm_install: false
          create_badges: false

workflows:
  version: 2
  lint_and_build:
    jobs:
      - build
