version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0-node  # Includes both Node.js and Java

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            npm install 

      - run:
          name: Run Snyk SCA Scan
          command: |
            npm install -g snyk
            npx snyk auth $SNYK_TOKEN
            npx snyk test || echo "Snyk found issues"
            
      - store_artifacts:
          path: reports
          destination: dependency-check-report

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
