version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:18.17.0

jobs:
  security-checks:
    executor: node_executor
    steps:
      - checkout

      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl unzip python3-pip
            pip install bandit

      - run:
          name: Install Gitleaks (Linux Binary)
          command: |
            curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_8.24.2_linux_x64.tar.gz -o gitleaks.tar.gz
            tar -xzf gitleaks.tar.gz
            chmod +x gitleaks
            sudo mv gitleaks /usr/local/bin/
            gitleaks version

      - run:
          name: Run Gitleaks on test cases
          command: |
            echo "Running Gitleaks in test-cases/gitleaks"
            gitleaks detect --source test-cases/gitleaks --no-banner --exit-code 1

      - run:
          name: Run Bandit on test cases
          command: |
            echo "Running Bandit in test-cases/bandit"
            bandit -r test-cases/bandit -ll || echo "Bandit found issues"

workflows:
  version: 2
  check-security:
    jobs:
      - security-checks
