version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:18.17.0

jobs:
  security-checks:
    executor: node_executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl unzip python3-pip
            pip install bandit
            npm install --save-dev eslint eslint-plugin-security

      - run:
          name: Run ESLint Security Scan
          command: |
            npx eslint test-cases/eslint --ext .js || echo "ESLint found issues"

      - run:
          name: Run Bandit
          command: |
            bandit -r test-cases/bandit -ll || echo "Bandit found issues"

      - run:
          name: Run OWASP Dependency Check
          command: |
            curl -sSLo dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
            unzip dependency-check.zip -d ./dependency-check
            ./dependency-check/bin/dependency-check.sh --project "hoobank" --scan . --format HTML --out reports

workflows:
  version: 2
  check-security:
    jobs:
      - security-checks
