version: 2.1

jobs:
  sqlmap_scan:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout

      - run:
          name: Install Docker, Python & SQLMap
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io python3 python3-pip
            sudo systemctl start docker
            sudo usermod -aG docker $USER
            pip3 install sqlmap

      - run:
          name: Start DVWA (Damn Vulnerable Web App)
          command: |
            docker run -d -p 8080:80 --name dvwa vulnerables/web-dvwa
            echo "Waiting for DVWA to start..."
            sleep 30  # wait for container to be ready

      - run:
          name: Run SQLMap against DVWA
          command: |
            TARGET_URL="http://localhost:8080/vulnerabilities/sqli/?id=1&Submit=Submit"
            sqlmap -u "$TARGET_URL" --data="id=1&Submit=Submit" --cookie="security=low; PHPSESSID=123" --batch --risk=3 --level=5 --output-dir=sqlmap-output

      - store_artifacts:
          path: sqlmap-output
          destination: sqlmap-report

workflows:
  version: 2
  scan-and-test:
    jobs:
      - sqlmap_scan
