version: 2.1

jobs:
  owasp_zap_scan:
    docker:
      - image: owasp/zap2docker-stable:2.10.0  # Using a specific version tag
    steps:
      - checkout

      - run:
          name: Start OWASP ZAP scan
          command: |
            TARGET_URL="https://hoooobank.netlify.app"
            zap-cli quick-scan --url "$TARGET_URL" --api-key $ZAP_API_KEY

      - store_artifacts:
          path: /zap/wrk
          destination: zap-report

workflows:
  version: 2
  scan-and-test:
    jobs:
      - owasp_zap_scan
