apiVersion: v1
kind: Service
metadata:
  name: snatchlock-service
spec:
  type: NodePort
  selector:
    app: snatchlock
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
